package com.couplecalendar.application.query.anniversary

import com.couplecalendar.application.dto.response.AnniversaryResponse
import com.couplecalendar.application.query.Query
import com.couplecalendar.application.query.QueryHandler
import com.couplecalendar.common.exception.ForbiddenException
import com.couplecalendar.domain.service.DDayCalculatorService
import com.couplecalendar.infrastructure.persistence.mapper.AnniversaryMapper
import com.couplecalendar.infrastructure.persistence.repository.JpaAnniversaryRepository
import com.couplecalendar.infrastructure.persistence.repository.JpaCoupleRepository
import org.springframework.stereotype.Component
import java.time.LocalDate
import java.util.UUID

data class GetAnniversariesQuery(
    val userId: UUID,
    val coupleId: UUID,
    val includeAutoGenerated: Boolean = true,
    val referenceDate: LocalDate = LocalDate.now()
) : Query<List<AnniversaryResponse>>

@Component
class GetAnniversariesQueryHandler(
    private val jpaAnniversaryRepository: JpaAnniversaryRepository,
    private val jpaCoupleRepository: JpaCoupleRepository,
    private val anniversaryMapper: AnniversaryMapper,
    private val dDayCalculatorService: DDayCalculatorService
) : QueryHandler<GetAnniversariesQuery, List<AnniversaryResponse>> {

    override fun handle(query: GetAnniversariesQuery): List<AnniversaryResponse> {
        val couple = jpaCoupleRepository.findById(query.coupleId).orElse(null)
            ?: return emptyList()

        if (couple.user1Id != query.userId && couple.user2Id != query.userId) {
            throw ForbiddenException("User is not a member of this couple")
        }

        val custom = jpaAnniversaryRepository.findByCoupleIdOrderByDateAsc(query.coupleId)
            .map { anniversaryMapper.toDomain(it) }
            .map { AnniversaryResponse.fromCustomAggregate(it, query.referenceDate) }

        val auto = if (query.includeAutoGenerated) {
            buildAutoAnniversaries(
                coupleId = query.coupleId,
                startDate = couple.startDate,
                referenceDate = query.referenceDate
            )
        } else emptyList()

        return (custom + auto).sortedBy { it.daysUntil }
    }

    private fun buildAutoAnniversaries(
        coupleId: UUID,
        startDate: LocalDate,
        referenceDate: LocalDate
    ): List<AnniversaryResponse> {
        val result = mutableListOf<AnniversaryResponse>()
        val horizon = referenceDate.plusYears(1)
        val daysFromStart = dDayCalculatorService.calculateDaysFromStart(startDate, referenceDate)

        // Day milestones (100/200/300/500/1000 etc.)
        val dayIntervals = listOf(100L, 200L, 300L, 500L, 1000L, 2000L, 3000L)
        dayIntervals
            .filter { it >= daysFromStart }
            .forEach { days ->
                val date = startDate.plusDays(days)
                if (!date.isAfter(horizon) && !date.isBefore(referenceDate)) {
                    result.add(
                        AnniversaryResponse.fromAuto(
                            coupleId = coupleId.toString(),
                            id = "auto-day-$days",
                            title = "${days}일 기념일",
                            date = date,
                            referenceDate = referenceDate
                        )
                    )
                }
            }

        // Year anniversaries (within 1 year horizon, we only have 1 upcoming yearly anniversary)
        val nextYearly = dDayCalculatorService.getNextAnniversary(startDate, referenceDate)
        if (!nextYearly.isAfter(horizon)) {
            val years = nextYearly.year - startDate.year
            if (years >= 1) {
                result.add(
                    AnniversaryResponse.fromAuto(
                        coupleId = coupleId.toString(),
                        id = "auto-year-$years",
                        title = "${years}주년",
                        date = nextYearly,
                        referenceDate = referenceDate
                    )
                )
            }
        }

        return result
    }
}
