import { AnniversaryDataSource } from "@/data/apis/AnniversaryDataSource";
import AnniversaryParser, { parseAnniversary } from "@/data/parsers/anniversaryParser";
import type Anniversary from "@/domain/entities/Anniversary";
import type {
	AnniversaryRepository,
	UpdateAnniversaryInput,
} from "@/domain/repositories/AnniversaryRepository";

/**
 * AnniversaryRepository implementation backed by the remote HTTP datasource.
 *
 * Maps the resulting DTOs into domain entities via the parser, and translates
 * domain inputs into request bodies. Only CUSTOM anniversaries are mutated —
 * the backend rejects AUTO mutations with 400 (`ensureNotAutoGenerated`).
 */
export class AnniversaryRepositoryImpl implements AnniversaryRepository {
	constructor(private readonly dataSource: AnniversaryDataSource = new AnniversaryDataSource()) {}

	async getAnniversaries(): Promise<Anniversary[]> {
		const dtos = await this.dataSource.getAnniversaries();
		return AnniversaryParser(dtos);
	}

	async addAnniversary(anniversary: Anniversary): Promise<Anniversary> {
		const created = await this.dataSource.addAnniversary({
			title: anniversary.title,
			date: anniversary.date,
			isRecurring: anniversary.isRecurring,
			description: anniversary.description,
		});
		return parseAnniversary(created);
	}

	async updateAnniversary(id: string, input: UpdateAnniversaryInput): Promise<Anniversary> {
		const updated = await this.dataSource.updateAnniversary(id, {
			title: input.title,
			date: input.date,
			isRecurring: input.isRecurring,
			description: input.description,
		});
		return parseAnniversary(updated);
	}

	async deleteAnniversary(id: string): Promise<void> {
		await this.dataSource.deleteAnniversary(id);
	}
}
