package com.couplecalendar.presentation.controller

import com.couplecalendar.application.dto.request.CreateAnniversaryRequest
import com.couplecalendar.application.dto.request.UpdateAnniversaryRequest
import com.couplecalendar.application.dto.response.AnniversaryResponse
import com.couplecalendar.application.service.AnniversariesService
import com.couplecalendar.common.security.CurrentUser
import com.couplecalendar.common.security.UserPrincipal
import jakarta.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PatchMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.ResponseStatus
import org.springframework.web.bind.annotation.RestController

@RestController
@RequestMapping("/api/anniversaries")
class AnniversariesController(
    private val anniversariesService: AnniversariesService
) {

    @GetMapping
    fun getAnniversaries(
        @CurrentUser user: UserPrincipal,
        @RequestParam(required = false, defaultValue = "true") includeAutoGenerated: Boolean
    ): List<AnniversaryResponse> =
        anniversariesService.getAnniversaries(user.id, includeAutoGenerated)

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    fun createAnniversary(
        @CurrentUser user: UserPrincipal,
        @Valid @RequestBody request: CreateAnniversaryRequest
    ): AnniversaryResponse =
        anniversariesService.createAnniversary(user.id, request)

    @PatchMapping("/{id}")
    fun updateAnniversary(
        @CurrentUser user: UserPrincipal,
        @PathVariable id: String,
        @Valid @RequestBody request: UpdateAnniversaryRequest
    ): AnniversaryResponse =
        anniversariesService.updateAnniversary(user.id, id, request)

    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    fun deleteAnniversary(
        @CurrentUser user: UserPrincipal,
        @PathVariable id: String
    ) {
        anniversariesService.deleteAnniversary(user.id, id)
    }
}
