import type { AnniversaryRepository } from "../repositories/AnniversaryRepository";

/**
 * Delete a custom anniversary by id.
 *
 * Guards against an empty id before delegating to the repository. AUTO
 * anniversaries cannot be deleted (backend `ensureNotAutoGenerated`); the
 * presentation layer hides the delete affordance for them.
 */
export class DeleteAnniversaryUseCase {
	constructor(private readonly anniversaryRepository: AnniversaryRepository) {}

	async execute(id: string): Promise<void> {
		if (!id.trim()) {
			throw new Error("삭제할 기념일을 찾을 수 없습니다.");
		}
		return this.anniversaryRepository.deleteAnniversary(id);
	}
}
