import {useQuery, useMutation, useQueryClient} from '@tanstack/react-query';
import {queryKeys} from '../queryClient';
import {fetchJson} from '../fetchJson';
import {useToastStore} from '../../store/useToastStore';
import type {
  Anniversary,
  CreateAnniversaryRequest,
  UpdateAnniversaryRequest,
} from '../../types';

// Helper: 일수 기준 D-day 문자열(예: D-30, D+10, D-Day)
export const formatDdayLabel = (daysUntil: number): string => {
  if (daysUntil === 0) return 'D-Day';
  if (daysUntil < 0) return `D+${Math.abs(daysUntil)}`;
  return `D-${daysUntil}`;
};

// Helper: 커플 시작일로부터 경과 일수 (로컬 계산용, 위젯에서 사용)
export const getDaysSince = (startDate: Date): number => {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const start = new Date(startDate);
  start.setHours(0, 0, 0, 0);
  const diffTime = today.getTime() - start.getTime();
  return Math.floor(diffTime / (1000 * 60 * 60 * 24)) + 1;
};

/**
 * GET /api/anniversaries
 * 커플에 속한 사용자 정의 기념일 목록 + (옵션) 자동 생성 기념일을 조회.
 * 서버에서 daysUntil 오름차순으로 정렬된 상태로 응답.
 */
export const useAnniversaries = (includeAutoGenerated: boolean = true) => {
  return useQuery({
    queryKey: queryKeys.anniversaries.list(includeAutoGenerated),
    queryFn: () =>
      fetchJson<Anniversary[]>('/api/anniversaries', {
        query: {includeAutoGenerated},
      }),
  });
};

/**
 * POST /api/anniversaries
 */
export const useCreateAnniversary = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (body: CreateAnniversaryRequest) =>
      fetchJson<Anniversary>('/api/anniversaries', {
        method: 'POST',
        body,
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({queryKey: queryKeys.anniversaries.all});
      useToastStore.getState().showToast('기념일이 등록되었습니다', 'success');
    },
  });
};

/**
 * PATCH /api/anniversaries/{id}
 * AUTO(id가 `auto-`로 시작) 항목은 백엔드에서 400으로 거부됨.
 */
export const useUpdateAnniversary = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({id, body}: {id: string; body: UpdateAnniversaryRequest}) =>
      fetchJson<Anniversary>(`/api/anniversaries/${id}`, {
        method: 'PATCH',
        body,
      }),
    onSuccess: (_data, variables) => {
      queryClient.invalidateQueries({queryKey: queryKeys.anniversaries.all});
      queryClient.invalidateQueries({
        queryKey: queryKeys.anniversaries.detail(variables.id),
      });
      useToastStore.getState().showToast('수정되었습니다', 'success');
    },
  });
};

/**
 * DELETE /api/anniversaries/{id}
 */
export const useDeleteAnniversary = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: string) =>
      fetchJson<void>(`/api/anniversaries/${id}`, {
        method: 'DELETE',
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({queryKey: queryKeys.anniversaries.all});
      useToastStore.getState().showToast('삭제되었습니다', 'success');
    },
  });
};
