import { HttpResponse, http } from "msw";
import type { AnniversaryResponse } from "@/data/dto/anniversary-response";
import { mockAnniversaries, mockCustomAnniversaries } from "../anniversaries.mock";
import { MOCK_IDS } from "../ids.mock";

interface CreateAnniversaryRequest {
	title: string;
	date: string;
	isRecurring?: boolean;
	description?: string | null;
}

type UpdateAnniversaryRequest = Partial<CreateAnniversaryRequest>;

const MS_PER_DAY = 86_400_000;

let anniversaryStore: AnniversaryResponse[] = structuredClone(mockAnniversaries);

const generateUuid = (): string => {
	if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
		return crypto.randomUUID();
	}
	return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
		const r = (Math.random() * 16) | 0;
		const v = c === "x" ? r : (r & 0x3) | 0x8;
		return v.toString(16);
	});
};

const calculateDaysUntil = (date: string): number => {
	const target = Date.parse(date);
	if (Number.isNaN(target)) return 0;
	const today = new Date();
	const todayUtc = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate());
	return Math.round((target - todayUtc) / MS_PER_DAY);
};

const isAutoId = (id: string): boolean => id.startsWith("auto-");

const sortByDaysUntilAsc = (list: AnniversaryResponse[]): AnniversaryResponse[] =>
	[...list].sort((a, b) => a.daysUntil - b.daysUntil);

export const anniversariesHandlers = [
	http.get("/api/anniversaries", ({ request }) => {
		const url = new URL(request.url);
		const includeRaw = url.searchParams.get("includeAutoGenerated");
		// Default true per backend spec
		const includeAuto = includeRaw === null ? true : includeRaw !== "false";

		const base = includeAuto ? anniversaryStore : anniversaryStore.filter((a) => a.type === "CUSTOM");

		// If the store does not contain AUTO items (e.g. after seed mutation),
		// fall back to canonical fixtures to match request expectation.
		const source = base.length > 0 ? base : includeAuto ? mockAnniversaries : mockCustomAnniversaries;

		return HttpResponse.json(sortByDaysUntilAsc(source));
	}),

	http.post("/api/anniversaries", async ({ request }) => {
		let body: CreateAnniversaryRequest | null = null;
		try {
			body = (await request.json()) as CreateAnniversaryRequest;
		} catch {
			return HttpResponse.json({ code: "BAD_REQUEST", message: "잘못된 요청 본문입니다" }, { status: 400 });
		}

		if (!body?.title || !body.date) {
			return HttpResponse.json({ code: "BAD_REQUEST", message: "필수 필드가 누락되었습니다" }, { status: 400 });
		}

		const created: AnniversaryResponse = {
			id: generateUuid(),
			coupleId: MOCK_IDS.couple,
			title: body.title,
			date: body.date,
			isRecurring: body.isRecurring ?? false,
			description: body.description ?? null,
			type: "CUSTOM",
			daysUntil: calculateDaysUntil(body.date),
		};

		anniversaryStore = [...anniversaryStore, created];
		return HttpResponse.json(created, { status: 201 });
	}),

	http.patch("/api/anniversaries/:id", async ({ params, request }) => {
		const { id } = params as { id: string };

		if (isAutoId(id)) {
			return HttpResponse.json(
				{ code: "BAD_REQUEST", message: "자동 기념일은 수정/삭제할 수 없습니다" },
				{ status: 400 },
			);
		}

		const index = anniversaryStore.findIndex((item) => item.id === id);
		if (index === -1) {
			return HttpResponse.json({ code: "NOT_FOUND", message: "기념일을 찾을 수 없습니다" }, { status: 404 });
		}

		let body: UpdateAnniversaryRequest | null = null;
		try {
			body = (await request.json()) as UpdateAnniversaryRequest;
		} catch {
			return HttpResponse.json({ code: "BAD_REQUEST", message: "잘못된 요청 본문입니다" }, { status: 400 });
		}

		const current = anniversaryStore[index];
		const merged: AnniversaryResponse = {
			...current,
			...(body?.title !== undefined ? { title: body.title } : {}),
			...(body?.date !== undefined ? { date: body.date } : {}),
			...(body?.isRecurring !== undefined ? { isRecurring: body.isRecurring } : {}),
			...(body?.description !== undefined ? { description: body.description } : {}),
		};

		if (body?.date !== undefined) {
			merged.daysUntil = calculateDaysUntil(body.date);
		}

		anniversaryStore = [...anniversaryStore.slice(0, index), merged, ...anniversaryStore.slice(index + 1)];
		return HttpResponse.json(merged);
	}),

	http.delete("/api/anniversaries/:id", ({ params }) => {
		const { id } = params as { id: string };

		if (isAutoId(id)) {
			return HttpResponse.json(
				{ code: "BAD_REQUEST", message: "자동 기념일은 수정/삭제할 수 없습니다" },
				{ status: 400 },
			);
		}

		const exists = anniversaryStore.some((item) => item.id === id);
		if (!exists) {
			return HttpResponse.json({ code: "NOT_FOUND", message: "기념일을 찾을 수 없습니다" }, { status: 404 });
		}

		anniversaryStore = anniversaryStore.filter((item) => item.id !== id);
		return new HttpResponse(null, { status: 204 });
	}),
];

/** Test-only helper. Resets the in-memory store back to its seeded state. */
export const __resetAnniversariesStoreForTests = () => {
	anniversaryStore = structuredClone(mockAnniversaries);
};
