"use client";

import { useState } from "react";
import { Badge, Button, Text } from "woosign-system";
import type Anniversary from "@/domain/entities/Anniversary";
import AnniversaryForm from "@/presentation/anniversaries/components/AnniversaryForm";
import useDeleteAnniversary from "@/presentation/anniversaries/hooks/useDeleteAnniversary";
import { formatDday } from "@/presentation/anniversaries/lib/anniversaryDisplay";
import { formatKoreanDate } from "@/shared/lib/date";

interface Props {
	/** 상세를 표시할 기념일. `null`이면 시트는 닫힌 상태. */
	anniversary: Anniversary | null;
	onClose: () => void;
}

const Row = ({ label, value }: { label: string; value: string }) => (
	<div className="flex flex-col gap-1">
		<Text as="p" variant="muted" style={{ fontSize: 12, color: "#9CA3AF" }}>
			{label}
		</Text>
		<Text as="p" variant="p" style={{ fontSize: 15, color: "#111827", whiteSpace: "pre-wrap" }}>
			{value}
		</Text>
	</div>
);

const AnniversaryDetailSheet = ({ anniversary, onClose }: Props) => {
	const open = anniversary !== null;
	// AUTO 마일스톤은 백엔드에서 수정/삭제 불가(ensureNotAutoGenerated).
	// CUSTOM만 편집 가능 — AUTO에는 수정/삭제 버튼을 노출하지 않는다.
	const isEditable = anniversary?.type === "CUSTOM";

	const [mode, setMode] = useState<"detail" | "edit">("detail");
	const [confirmingDelete, setConfirmingDelete] = useState(false);
	const {
		mutate: deleteAnniversary,
		isPending: isDeleting,
		error: deleteError,
	} = useDeleteAnniversary();

	// 다른 기념일이 열릴 때 임시 UI 상태를 렌더 중 초기화 (React 권장 패턴).
	const [lastId, setLastId] = useState<string | null>(anniversary?.id ?? null);
	if ((anniversary?.id ?? null) !== lastId) {
		setLastId(anniversary?.id ?? null);
		setMode("detail");
		setConfirmingDelete(false);
	}

	const handleClose = () => {
		setMode("detail");
		setConfirmingDelete(false);
		onClose();
	};

	const handleDelete = () => {
		if (!anniversary) return;
		if (!confirmingDelete) {
			setConfirmingDelete(true);
			return;
		}
		deleteAnniversary(anniversary.id, { onSuccess: handleClose });
	};

	return (
		<>
			<button
				type="button"
				aria-label="배경"
				tabIndex={-1}
				onClick={handleClose}
				className={`fixed inset-0 z-40 bg-black/40 transition-opacity duration-300 ${
					open ? "pointer-events-auto opacity-100" : "pointer-events-none opacity-0"
				}`}
			/>
			<div
				role="dialog"
				aria-modal="true"
				aria-hidden={!open}
				className={`fixed inset-x-0 bottom-0 z-50 mx-auto flex max-h-[90dvh] w-full max-w-[420px] flex-col rounded-t-2xl bg-white shadow-2xl transition-transform duration-300 ease-out ${
					open ? "translate-y-0" : "pointer-events-none translate-y-full"
				}`}
			>
				<header className="flex shrink-0 items-center justify-between px-5 pt-4 pb-3">
					{mode === "edit" ? (
						<Text as="p" variant="p" weight="semibold" style={{ color: "#111827" }}>
							기념일 수정
						</Text>
					) : anniversary ? (
						<Badge variant="secondary">
							{anniversary.type === "AUTO" ? "자동 기념일" : "내 기념일"}
						</Badge>
					) : (
						<span />
					)}
					<button
						type="button"
						aria-label="닫기"
						onClick={handleClose}
						className="grid size-8 place-items-center text-2xl text-neutral-800"
					>
						×
					</button>
				</header>

				{anniversary && mode === "edit" && isEditable ? (
					<AnniversaryForm
						anniversary={anniversary}
						onSuccess={handleClose}
						bodyClassName="flex min-h-0 flex-1 flex-col gap-7 overflow-y-auto px-5 pt-2 pb-4"
						footerClassName="shrink-0 border-neutral-100 border-t bg-white px-5 py-4"
					/>
				) : null}

				{anniversary && mode === "detail" ? (
					<>
						<div className="flex min-h-0 flex-1 flex-col gap-6 overflow-y-auto px-5 pt-1 pb-4">
							<div className="flex flex-col gap-1">
								<Text as="h2" variant="h2" weight="bold" style={{ fontSize: 22, color: "#111827" }}>
									{anniversary.title}
								</Text>
								<Text as="p" variant="small" weight="semibold" style={{ color: "#ef6f5b" }}>
									{formatDday(anniversary.daysUntil)}
								</Text>
							</div>

							<Row label="날짜" value={formatKoreanDate(anniversary.date)} />
							{anniversary.isRecurring ? <Row label="반복" value="매년 반복" /> : null}
							{anniversary.description ? (
								<Row label="메모" value={anniversary.description} />
							) : null}

							{!isEditable ? (
								<Text as="p" variant="small" style={{ color: "#9CA3AF" }}>
									자동으로 생성된 기념일은 수정하거나 삭제할 수 없어요.
								</Text>
							) : null}
						</div>

						{isEditable ? (
							<div className="shrink-0 border-neutral-100 border-t bg-white px-5 py-4">
								{deleteError ? (
									<Text as="p" variant="small" className="mb-2" style={{ color: "#dc2626" }}>
										{deleteError.message}
									</Text>
								) : null}
								{confirmingDelete ? (
									<Text as="p" variant="small" className="mb-2" style={{ color: "#dc2626" }}>
										정말 삭제할까요? 한 번 더 누르면 삭제됩니다.
									</Text>
								) : null}
								<div className="flex gap-2">
									<Button
										variant="outline"
										size="lg"
										fullWidth
										disabled={isDeleting}
										onPress={() => setMode("edit")}
									>
										수정
									</Button>
									<Button
										variant="destructive"
										size="lg"
										fullWidth
										disabled={isDeleting}
										onPress={handleDelete}
									>
										{isDeleting ? "삭제 중..." : confirmingDelete ? "삭제 확인" : "삭제"}
									</Button>
								</div>
							</div>
						) : null}
					</>
				) : null}
			</div>
		</>
	);
};

export default AnniversaryDetailSheet;
