"use client";

import { useState } from "react";
import type Anniversary from "@/domain/entities/Anniversary";
import { CloseIcon } from "@/presentation/components/icons";
import AnniversaryForm from "@/presentation/anniversaries/components/AnniversaryForm";
import useDeleteAnniversary from "@/presentation/anniversaries/hooks/useDeleteAnniversary";
import { formatDday } from "@/presentation/anniversaries/lib/anniversaryDisplay";
import { formatKoreanDate } from "@/shared/lib/date";

interface Props {
	/** 상세를 표시할 기념일. `null`이면 시트는 닫힌 상태. */
	anniversary: Anniversary | null;
	onClose: () => void;
}

const Row = ({ label, value }: { label: string; value: string }) => (
	<div className="flex flex-col gap-1">
		<p style={{ fontSize: 12, color: "var(--text-tertiary)" }}>{label}</p>
		<p style={{ fontSize: 15, color: "var(--text-brand)", whiteSpace: "pre-wrap" }}>{value}</p>
	</div>
);

const AnniversaryDetailSheet = ({ anniversary, onClose }: Props) => {
	const open = anniversary !== null;
	// AUTO 마일스톤은 백엔드에서 수정/삭제 불가(ensureNotAutoGenerated).
	// CUSTOM만 편집 가능 — AUTO에는 수정/삭제 버튼을 노출하지 않는다.
	const isEditable = anniversary?.type === "CUSTOM";

	const [mode, setMode] = useState<"detail" | "edit">("detail");
	const [confirmingDelete, setConfirmingDelete] = useState(false);
	const {
		mutate: deleteAnniversary,
		isPending: isDeleting,
		error: deleteError,
	} = useDeleteAnniversary();

	// 다른 기념일이 열릴 때 임시 UI 상태를 렌더 중 초기화 (React 권장 패턴).
	const [lastId, setLastId] = useState<string | null>(anniversary?.id ?? null);
	if ((anniversary?.id ?? null) !== lastId) {
		setLastId(anniversary?.id ?? null);
		setMode("detail");
		setConfirmingDelete(false);
	}

	const handleClose = () => {
		setMode("detail");
		setConfirmingDelete(false);
		onClose();
	};

	const handleDelete = () => {
		if (!anniversary) return;
		if (!confirmingDelete) {
			setConfirmingDelete(true);
			return;
		}
		deleteAnniversary(anniversary.id, { onSuccess: handleClose });
	};

	return (
		<>
			<button
				type="button"
				aria-label="배경"
				tabIndex={-1}
				onClick={handleClose}
				className={`fixed inset-0 z-40 transition-opacity duration-300 ${
					open ? "pointer-events-auto opacity-100" : "pointer-events-none opacity-0"
				}`}
				style={{ background: "rgba(0,0,0,0.6)" }}
			/>
			<div
				role="dialog"
				aria-modal="true"
				aria-hidden={!open}
				className={`fixed inset-x-0 bottom-0 z-50 mx-auto flex max-h-[90dvh] w-full max-w-[420px] flex-col rounded-t-2xl transition-transform duration-300 ease-out ${
					open ? "translate-y-0" : "pointer-events-none translate-y-full"
				}`}
				style={{
					background: "var(--bg-section)",
					borderTop: "1px solid rgba(255,255,255,0.08)",
					boxShadow: "var(--shadow-modal)",
				}}
			>
				<header className="flex shrink-0 items-center justify-between px-5 pt-4 pb-3">
					{mode === "edit" ? (
						<span style={{ fontSize: 16, fontWeight: 600, color: "var(--text-brand)" }}>기념일 수정</span>
					) : anniversary ? (
						<span
							className="rounded-full px-2.5 py-1"
							style={{ fontSize: 12, background: "rgba(255,255,255,0.08)", color: "var(--text-secondary)" }}
						>
							{anniversary.type === "AUTO" ? "자동 기념일" : "내 기념일"}
						</span>
					) : (
						<span />
					)}
					<button
						type="button"
						aria-label="닫기"
						onClick={handleClose}
						className="grid size-8 place-items-center"
						style={{ color: "var(--text-secondary)" }}
					>
						<CloseIcon s={20} />
					</button>
				</header>

				{anniversary && mode === "edit" && isEditable ? (
					<AnniversaryForm
						anniversary={anniversary}
						onSuccess={handleClose}
						bodyClassName="flex min-h-0 flex-1 flex-col gap-7 overflow-y-auto px-5 pt-2 pb-4 dark-scroll"
						footerClassName="shrink-0 px-5 pt-4 pb-[calc(env(safe-area-inset-bottom)_+_1rem)]"
					/>
				) : null}

				{anniversary && mode === "detail" ? (
					<>
						<div className="flex min-h-0 flex-1 flex-col gap-6 overflow-y-auto px-5 pt-1 pb-[calc(env(safe-area-inset-bottom)_+_1rem)] dark-scroll">
							<div className="flex flex-col gap-1">
								<h2 style={{ fontSize: 22, fontWeight: 700, color: "var(--text-brand)" }}>{anniversary.title}</h2>
								<p style={{ fontSize: 14, fontWeight: 600, color: "var(--action-primary)" }}>
									{formatDday(anniversary.daysUntil)}
								</p>
							</div>

							<Row label="날짜" value={formatKoreanDate(anniversary.date)} />
							{anniversary.isRecurring ? <Row label="반복" value="매년 반복" /> : null}
							{anniversary.description ? <Row label="메모" value={anniversary.description} /> : null}

							{!isEditable ? (
								<p className="wb-body-sm" style={{ color: "var(--text-tertiary)" }}>
									자동으로 생성된 기념일은 수정하거나 삭제할 수 없어요.
								</p>
							) : null}
						</div>

						{isEditable ? (
							<div className="shrink-0 px-5 pt-4 pb-[calc(env(safe-area-inset-bottom)_+_1rem)]">
								{deleteError ? (
									<p className="wb-body-sm mb-2" style={{ color: "var(--error-red)" }}>
										{deleteError.message}
									</p>
								) : null}
								{confirmingDelete ? (
									<p className="wb-body-sm mb-2" style={{ color: "var(--error-red)" }}>
										정말 삭제할까요? 한 번 더 누르면 삭제됩니다.
									</p>
								) : null}
								<div className="flex gap-2">
									<button
										type="button"
										onClick={() => setMode("edit")}
										disabled={isDeleting}
										className="wb-btn wb-btn--secondary wb-btn--lg"
										style={{ flex: 1 }}
									>
										수정
									</button>
									<button
										type="button"
										onClick={handleDelete}
										disabled={isDeleting}
										className="wb-btn wb-btn--danger wb-btn--lg"
										style={{ flex: 1 }}
									>
										{isDeleting ? "삭제 중..." : confirmingDelete ? "삭제 확인" : "삭제"}
									</button>
								</div>
							</div>
						) : null}
					</>
				) : null}
			</div>
		</>
	);
};

export default AnniversaryDetailSheet;
