package com.couplecalendar.application.service

import com.couplecalendar.application.command.anniversary.CreateAnniversaryCommand
import com.couplecalendar.application.command.anniversary.CreateAnniversaryCommandHandler
import com.couplecalendar.application.command.anniversary.DeleteAnniversaryCommand
import com.couplecalendar.application.command.anniversary.DeleteAnniversaryCommandHandler
import com.couplecalendar.application.command.anniversary.UpdateAnniversaryCommand
import com.couplecalendar.application.command.anniversary.UpdateAnniversaryCommandHandler
import com.couplecalendar.application.dto.request.CreateAnniversaryRequest
import com.couplecalendar.application.dto.request.UpdateAnniversaryRequest
import com.couplecalendar.application.dto.response.AnniversaryResponse
import com.couplecalendar.application.query.anniversary.GetAnniversariesQuery
import com.couplecalendar.application.query.anniversary.GetAnniversariesQueryHandler
import com.couplecalendar.common.exception.BadRequestException
import org.springframework.stereotype.Service
import java.time.LocalDate
import java.util.UUID

@Service
class AnniversariesService(
    private val createAnniversaryCommandHandler: CreateAnniversaryCommandHandler,
    private val updateAnniversaryCommandHandler: UpdateAnniversaryCommandHandler,
    private val deleteAnniversaryCommandHandler: DeleteAnniversaryCommandHandler,
    private val getAnniversariesQueryHandler: GetAnniversariesQueryHandler,
    private val usersService: UsersService
) {

    fun getAnniversaries(userId: UUID, includeAutoGenerated: Boolean): List<AnniversaryResponse> {
        val coupleId = requireCoupleId(userId)
        return getAnniversariesQueryHandler.handle(
            GetAnniversariesQuery(
                userId = userId,
                coupleId = coupleId,
                includeAutoGenerated = includeAutoGenerated
            )
        )
    }

    fun createAnniversary(userId: UUID, request: CreateAnniversaryRequest): AnniversaryResponse {
        val coupleId = requireCoupleId(userId)

        val date = parseDate(request.date)

        val command = CreateAnniversaryCommand(
            userId = userId,
            coupleId = coupleId,
            title = request.title,
            date = date,
            isRecurring = request.isRecurring,
            description = request.description
        )

        val anniversary = createAnniversaryCommandHandler.handle(command)
        return AnniversaryResponse.fromCustomAggregate(anniversary)
    }

    fun updateAnniversary(
        userId: UUID,
        anniversaryId: String,
        request: UpdateAnniversaryRequest
    ): AnniversaryResponse {
        ensureNotAutoGenerated(anniversaryId)
        val coupleId = requireCoupleId(userId)

        val id = parseUuid(anniversaryId)

        val command = UpdateAnniversaryCommand(
            userId = userId,
            coupleId = coupleId,
            anniversaryId = id,
            title = request.title,
            date = request.date?.let { parseDate(it) },
            isRecurring = request.isRecurring,
            description = request.description
        )

        val anniversary = updateAnniversaryCommandHandler.handle(command)
        return AnniversaryResponse.fromCustomAggregate(anniversary)
    }

    fun deleteAnniversary(userId: UUID, anniversaryId: String) {
        ensureNotAutoGenerated(anniversaryId)
        val coupleId = requireCoupleId(userId)
        val id = parseUuid(anniversaryId)

        deleteAnniversaryCommandHandler.handle(
            DeleteAnniversaryCommand(userId, coupleId, id)
        )
    }

    private fun ensureNotAutoGenerated(id: String) {
        if (id.startsWith("auto-")) {
            throw BadRequestException("자동 기념일은 수정/삭제할 수 없습니다")
        }
    }

    private fun parseUuid(id: String): UUID = try {
        UUID.fromString(id)
    } catch (e: IllegalArgumentException) {
        throw BadRequestException("Invalid anniversary id")
    }

    private fun parseDate(value: String): LocalDate = try {
        LocalDate.parse(value)
    } catch (e: Exception) {
        throw BadRequestException("Invalid date format (expected YYYY-MM-DD)")
    }

    private fun requireCoupleId(userId: UUID): UUID {
        return usersService.getUserCoupleId(userId)
            ?: throw BadRequestException("User is not in a couple")
    }
}
