import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  TouchableOpacity,
  Alert,
  ActivityIndicator,
} from 'react-native';
import {Card} from '../../../shared/ui';
import {DdayBadge} from '../../../entities/anniversary';
import {
  useAnniversaries,
  useDeleteAnniversary,
} from '../../../shared/api';
import type {Anniversary} from '../../../shared/types';

interface AnniversaryListProps {
  onPressItem?: (anniversary: Anniversary) => void;
  includeAutoGenerated?: boolean;
}

export const AnniversaryList: React.FC<AnniversaryListProps> = ({
  onPressItem,
  includeAutoGenerated = true,
}) => {
  const {
    data: anniversaries,
    isLoading,
    isError,
    refetch,
  } = useAnniversaries(includeAutoGenerated);
  const deleteAnniversary = useDeleteAnniversary();

  const handleLongPress = (item: Anniversary) => {
    if (item.type === 'AUTO') {
      // 자동 기념일은 수정/삭제 불가 (서버에서도 400 반환)
      Alert.alert('자동 기념일', '자동 기념일은 수정/삭제할 수 없습니다.');
      return;
    }

    Alert.alert(item.title, '어떤 작업을 하시겠어요?', [
      {text: '취소', style: 'cancel'},
      {
        text: '상세 보기',
        onPress: () => onPressItem?.(item),
      },
      {
        text: '삭제',
        style: 'destructive',
        onPress: () => {
          Alert.alert('기념일 삭제', '정말 삭제하시겠습니까?', [
            {text: '취소', style: 'cancel'},
            {
              text: '삭제',
              style: 'destructive',
              onPress: () => {
                // 에러/성공 토스트는 전역 핸들러와 hook onSuccess에서 처리
                deleteAnniversary.mutate(item.id);
              },
            },
          ]);
        },
      },
    ]);
  };

  if (isLoading) {
    return (
      <Card style={styles.container}>
        <ActivityIndicator color="#FF8B94" />
      </Card>
    );
  }

  if (isError) {
    return (
      <Card style={styles.container}>
        <Text style={styles.stateText}>불러올 수 없습니다</Text>
        <TouchableOpacity onPress={() => refetch()} style={styles.retryButton}>
          <Text style={styles.retryText}>다시 시도</Text>
        </TouchableOpacity>
      </Card>
    );
  }

  if (!anniversaries || anniversaries.length === 0) {
    return (
      <Card style={styles.container}>
        <Text style={styles.stateText}>등록된 기념일이 없습니다</Text>
      </Card>
    );
  }

  const renderItem = ({item}: {item: Anniversary}) => (
    <TouchableOpacity
      style={styles.item}
      activeOpacity={0.7}
      onPress={() => onPressItem?.(item)}
      onLongPress={() => handleLongPress(item)}>
      <View style={styles.itemInfo}>
        <View style={styles.itemTitleRow}>
          <Text style={styles.itemTitle} numberOfLines={1}>
            {item.title}
          </Text>
          {item.type === 'AUTO' && (
            <View style={styles.autoBadge}>
              <Text style={styles.autoBadgeText}>자동</Text>
            </View>
          )}
        </View>
        <Text style={styles.itemDate}>
          {new Date(`${item.date}T00:00:00`).toLocaleDateString('ko-KR', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          })}
          {item.isRecurring ? '  · 매년 반복' : ''}
        </Text>
      </View>
      <DdayBadge days={item.daysUntil} size="small" type={item.type} />
    </TouchableOpacity>
  );

  return (
    <Card style={styles.container}>
      <Text style={styles.title}>전체 기념일</Text>
      <FlatList
        data={anniversaries}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
        scrollEnabled={false}
        ItemSeparatorComponent={() => <View style={styles.separator} />}
      />
    </Card>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 16,
  },
  title: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 12,
  },
  item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
  },
  itemInfo: {
    flex: 1,
    marginRight: 12,
  },
  itemTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  itemTitle: {
    fontSize: 15,
    fontWeight: '500',
    color: '#333333',
    flexShrink: 1,
  },
  autoBadge: {
    marginLeft: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: '#E8F4FA',
  },
  autoBadgeText: {
    fontSize: 10,
    color: '#4A90B8',
    fontWeight: '600',
  },
  itemDate: {
    fontSize: 12,
    color: '#999999',
  },
  separator: {
    height: 1,
    backgroundColor: '#F0F0F0',
  },
  stateText: {
    fontSize: 14,
    color: '#999999',
    textAlign: 'center',
    paddingVertical: 20,
  },
  retryButton: {
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#FFE5E9',
  },
  retryText: {
    color: '#FF6B6B',
    fontSize: 13,
    fontWeight: '600',
  },
});
