import {
  QueryCache,
  QueryClient,
  MutationCache,
} from '@tanstack/react-query';
import {useToastStore} from '../store/useToastStore';
import {useAuthStore} from '../store/useAuthStore';
import {
  ApiError,
  NetworkError,
  classifyError,
  getErrorMessage,
} from '../lib/errors';

/**
 * Mutation의 meta 타입 확장.
 * - disableGlobalErrorToast: true 설정 시 전역 에러 토스트 skip
 *   (예: 폼 유효성 에러를 필드에 직접 표시하는 경우)
 */
declare module '@tanstack/react-query' {
  interface Register {
    mutationMeta: {
      disableGlobalErrorToast?: boolean;
    };
    queryMeta: {
      disableGlobalErrorToast?: boolean;
    };
  }
}

const shouldSkipGlobalToast = (source: {
  options?: {meta?: Record<string, unknown>};
}): boolean => {
  const meta = source?.options?.meta as
    | {disableGlobalErrorToast?: boolean}
    | undefined;
  return meta?.disableGlobalErrorToast === true;
};

/**
 * Query 전역 에러 핸들러.
 * - 네트워크/알수없는 에러만 토스트 (사용자가 재시도하거나 화면이 로딩 실패 상태를 보여줄 수 있게)
 * - 비즈니스 에러(4xx)는 개별 컴포넌트의 isError UI로 처리하도록 조용히 통과
 * - 401은 fetchJson에서 이미 logout을 트리거하므로 여기서는 토스트만 추가
 */
const queryCache = new QueryCache({
  onError: (error, query) => {
    if (shouldSkipGlobalToast(query)) {
      return;
    }

    const classified = classifyError(error);
    const {showToast} = useToastStore.getState();

    if (classified instanceof NetworkError) {
      showToast('네트워크에 연결할 수 없습니다', 'error');
      return;
    }

    if (classified instanceof ApiError && classified.status === 401) {
      showToast('로그인이 필요합니다', 'warning');
      return;
    }

    // 비즈니스(ApiError 4xx/5xx)는 각 화면에서 isError로 렌더링하는 게 일반적이므로
    // 여기서는 토스트를 띄우지 않는다. (disableGlobalErrorToast=false라도)
    // 단, ApiError가 아닌 UnknownError는 토스트로 알림.
    if (!(classified instanceof ApiError)) {
      showToast(getErrorMessage(classified), 'error');
    }
  },
});

/**
 * Mutation 전역 에러 핸들러.
 * - 401: fetchJson에서 이미 logout 처리됨 → 토스트만
 * - NetworkError: "네트워크에 연결할 수 없습니다"
 * - ApiError(비즈니스): error.message 토스트
 * - 그 외: UnknownError 메시지
 * meta.disableGlobalErrorToast=true 이면 skip.
 */
const mutationCache = new MutationCache({
  onError: (error, _variables, _context, mutation) => {
    if (shouldSkipGlobalToast(mutation)) {
      return;
    }

    const classified = classifyError(error);
    const {showToast} = useToastStore.getState();

    if (classified instanceof NetworkError) {
      showToast('네트워크에 연결할 수 없습니다', 'error');
      return;
    }

    if (classified instanceof ApiError) {
      if (classified.status === 401) {
        // fetchJson에서 logout은 이미 호출됨. 여기서는 한 번 더 보장.
        useAuthStore.getState().logout();
        showToast('로그인이 필요합니다', 'warning');
        return;
      }
      showToast(classified.message || '요청을 처리할 수 없습니다', 'error');
      return;
    }

    showToast(getErrorMessage(classified), 'error');
  },
});

export const queryClient = new QueryClient({
  queryCache,
  mutationCache,
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60 * 5, // 5 minutes
      gcTime: 1000 * 60 * 30, // 30 minutes
      retry: 2,
      refetchOnWindowFocus: false,
    },
    mutations: {
      retry: 1,
    },
  },
});

// Query Keys
export const queryKeys = {
  events: {
    all: ['events'] as const,
    byMonth: (year: number, month: number) =>
      ['events', 'month', year, month] as const,
    byDate: (dateKey: string) => ['events', 'date', dateKey] as const,
    detail: (id: string) => ['events', 'detail', id] as const,
  },
  anniversaries: {
    all: ['anniversaries'] as const,
    list: (includeAutoGenerated: boolean) =>
      ['anniversaries', 'list', includeAutoGenerated] as const,
    detail: (id: string) => ['anniversaries', 'detail', id] as const,
  },
  couple: {
    current: ['couple', 'current'] as const,
    partner: ['couple', 'partner'] as const,
  },
  user: {
    current: ['user', 'current'] as const,
  },
};
