import type Anniversary from "../entities/Anniversary";

/**
 * Partial update payload for an existing anniversary. Every field is optional;
 * only the provided fields are sent to the backend (PATCH semantics).
 *
 * Domain language input — not a DTO. `date` follows the anniversary convention
 * (a LocalDate `yyyy-mm-dd` string), distinct from Event's ISO 8601 timestamps.
 */
export interface UpdateAnniversaryInput {
	title?: string;
	date?: string;
	isRecurring?: boolean;
	description?: string | null;
}

/**
 * Repository contract for the Anniversary aggregate.
 *
 * Domain layer interface — implementations live under `data/repositories/`
 * and inject a concrete data source. Only CUSTOM anniversaries can be updated
 * or deleted; AUTO milestones are read-only (enforced server-side via
 * `ensureNotAutoGenerated`).
 */
export interface AnniversaryRepository {
	getAnniversaries(): Promise<Anniversary[]>;
	addAnniversary(anniversary: Anniversary): Promise<Anniversary>;
	updateAnniversary(id: string, input: UpdateAnniversaryInput): Promise<Anniversary>;
	deleteAnniversary(id: string): Promise<void>;
}
